import csv
import os


CSV_FILE_NAME = 'mars_weathers_data.csv'
SQL_FILE_NAME = 'mars_weather_summary.sql'
TABLE_NAME = 'mars_weather'


def parse_int(value):
    value = value.strip()

    if value == '':
        return 0

    try:
        return int(value)
    except ValueError:
        return 0


def parse_float(value):
    value = value.strip()

    if value == '':
        return 0.0

    try:
        return float(value)
    except ValueError:
        return 0.0


def escape_sql_text(value):
    return value.replace('\\', '\\\\').replace("'", "''")


def read_weather_data():
    weather_data = []

    try:
        if not os.path.exists(CSV_FILE_NAME):
            print(f'[오류] {CSV_FILE_NAME} 파일을 찾을 수 없습니다.')
            return []

        with open(CSV_FILE_NAME, 'r', encoding='utf-8-sig', newline='') as csv_file:
            reader = csv.DictReader(csv_file)

            if reader.fieldnames is None:
                print('[오류] CSV 파일에 헤더가 없습니다.')
                return []

            required_columns = ['weather_id', 'mars_date', 'temp', 'stom']

            for column in required_columns:
                if column not in reader.fieldnames:
                    print(f'[오류] CSV 파일에 {column} 컬럼이 없습니다.')
                    print(f'현재 CSV 컬럼: {reader.fieldnames}')
                    return []

            for row in reader:
                weather_data.append({
                    'weather_id': parse_int(row['weather_id']),
                    'mars_date': row['mars_date'].strip(),
                    'temp': parse_float(row['temp']),
                    'storm': parse_int(row['stom'])
                })

    except OSError as error:
        print(f'[오류] CSV 파일을 읽는 중 문제가 발생했습니다: {error}')
        return []

    return weather_data


def create_table_sql():
    return f'''CREATE TABLE IF NOT EXISTS {TABLE_NAME} (
    weather_id INT AUTO_INCREMENT PRIMARY KEY,
    mars_date DATETIME NOT NULL,
    temp FLOAT,
    storm INT
);
'''


def create_insert_sql(weather):
    mars_date = escape_sql_text(weather['mars_date'])
    temp = weather['temp']
    storm = weather['storm']

    return (
        f"INSERT INTO {TABLE_NAME} (mars_date, temp, storm) "
        f"VALUES ('{mars_date}', {temp}, {storm});"
    )


def save_sql_file(weather_data):
    try:
        with open(SQL_FILE_NAME, 'w', encoding='utf-8') as sql_file:
            sql_file.write('-- Mars weather table create and insert script\n')
            sql_file.write('-- Generated by mars_weather_summary.py\n\n')

            sql_file.write(create_table_sql())
            sql_file.write('\n')

            for weather in weather_data:
                sql_file.write(create_insert_sql(weather))
                sql_file.write('\n')

        print(f'SQL 파일 저장 완료: {SQL_FILE_NAME}')

    except OSError as error:
        print(f'[오류] SQL 파일을 저장하는 중 문제가 발생했습니다: {error}')


def print_weather_data(weather_data):
    print('mars_weather_data.csv 파일 내용')
    print('-' * 60)

    for weather in weather_data:
        print(
            f"weather_id={weather['weather_id']}, "
            f"mars_date={weather['mars_date']}, "
            f"temp={weather['temp']}, "
            f"storm={weather['storm']}"
        )

    print('-' * 60)
    print(f'총 데이터 수: {len(weather_data)}')


def main():
    weather_data = read_weather_data()

    if len(weather_data) == 0:
        print('[오류] 처리할 날씨 데이터가 없습니다.')
        return

    print_weather_data(weather_data)
    save_sql_file(weather_data)


if __name__ == '__main__':
    main()